schema-version: v3
kind: action
metadata:
  name: action-understanding-object-oriented-code
  display-name: action-understanding-object-oriented-code
  description: Analyze an object-oriented design recursively and generate documentation.
  version: 0.0.1
spec:
  type: python
  docs:
    pt-br: docs/pt-br/docs.md
    en-us: docs/en-us/docs.md
  inputs:
    - label: Execute Slug
      name: execute_slug
      type: text
      required: true
      default: rqc-domain-documentation
      help: "Slug de execução para o comando remoto."

    - label: Account Slug
      name: account_slug
      type: text
      required: true
      default: growth-demo
      help: "Slug da conta para autenticação na API."

    - label: Client ID
      name: client_id
      type: text
      required: true
      default: 2162e494-690f-4507-9c3b-ac9a1612a61a
      help: "ID do cliente para autenticação na API."

    - label: Client Secret
      name: client_secret
      type: password
      required: true
      default: 7MLZnp6892OX5lPrBXGRTbn09412k89zmoTrBNlM8W1Xt4VnqwZ4rVnJAYU4iE40
      help: "Segredo do cliente para autenticação na API."

    - label: Project Path
      name: project_path
      type: text
      required: false
      default: "./file-to-analyze/Pottencial.GG/Application"
      help: "Caminho para a pasta contendo os arquivos a serem processados."

    - label: Controller Path
      name: controller_path
      type: text
      required: true
      default: "./file-to-analyze/Pottencial.GG/Application/Pottencial.GG.Api/Controllers/LimiteTaxaController.cs"
      help: "Informe a extensão do arquivo (ex.: .cs, .json, .tar.gz)."
  python:
    workdir: .
    script: script.py
